#!/bin/sh

export HOME=/root
export SHELL=/bin/bash
export LANG=en_US.UTF-8
export PATH=/bin:/usr/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/sbin
export XDG_RUNTIME_DIR=/run/user/0

mkdir -p /dev/shm
mount -t tmpfs tmpfs /dev/shm
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

mkdir -p /tmp/.X11-unix /tmp/.ICE-unix "$HOME/.config/dconf" \
    /run/dbus /var/lib/dbus "$XDG_RUNTIME_DIR"
chmod 01777 /tmp/.X11-unix
chmod 0777 /tmp/.ICE-unix
chmod 0700 "$XDG_RUNTIME_DIR"

dbus-uuidgen --ensure
dbus-daemon --system --fork
udevd &

while [ ! -e /run/udev/control ]; do
    sleep 0.1
done

udevadm trigger --action=add
udevadm settle

exec runuser -l root -c /usr/lib/aether/start-xfce4-session
