#!/bin/sh

export XDG_SESSION_TYPE=wayland
export XDG_CONFIG_DIRS=/etc/xdg
export NO_AT_BRIDGE=1
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24
export XCURSOR_PATH=/usr/share/icons:/usr/share/pixmaps
export SDL_VIDEODRIVER=wayland
export SDL_AUDIODRIVER=pipewire

exec dbus-run-session -- seatd-launch -- startxfce4 --wayland
