#!/bin/sh

export XDG_SESSION_TYPE=wayland
export XDG_CONFIG_DIRS=/etc/xdg
export NO_AT_BRIDGE=1
export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24
export XCURSOR_PATH=/usr/share/icons:/usr/share/pixmaps
export SDL_VIDEODRIVER=wayland
export SDL_AUDIODRIVER=dummy
export SEATD_VTBOUND=0
export XDG_RUNTIME_DIR=/run/user/0

# Software rendering fallback (only needed if virtio-gpu PRIME export fails)
# export WLR_RENDERER=pixman
# export WLR_RENDERER_ALLOW_SOFTWARE=1
if [ ! -d /dev/input ]; then
    export WLR_LIBINPUT_NO_DEVICES=1
fi

mkdir -p "$XDG_RUNTIME_DIR"
chmod 0700 "$XDG_RUNTIME_DIR"

exec dbus-run-session -- labwc
